#include "ThemeManager.h"
#include <QFile>
#include <QApplication>

ThemeManager::ThemeManager() {}

void ThemeManager::applyTheme(QApplication *app) {
    QString styleSheet = 
        "QMainWindow {"
        "   background-color: #0b0e17;"
        "}"
        ""
        "QWidget {"
        "   background-color: #0b0e17;"
        "   color: #eef2ff;"
        "   font-family: 'Segoe UI', 'Inter', sans-serif;"
        "}"
        ""
        "QPushButton {"
        "   background-color: #3b82f6;"
        "   color: white;"
        "   border: none;"
        "   border-radius: 40px;"
        "   padding: 8px 20px;"
        "   font-weight: bold;"
        "}"
        ""
        "QPushButton:hover {"
        "   background-color: #2563eb;"
        "}"
        ""
        "QPushButton:flat {"
        "   background-color: transparent;"
        "   border: 1px solid #3b82f6;"
        "   color: #3b82f6;"
        "}"
        ""
        "QGroupBox {"
        "   background-color: rgba(18, 25, 45, 0.6);"
        "   border: 1px solid rgba(59, 130, 246, 0.2);"
        "   border-radius: 16px;"
        "   margin-top: 12px;"
        "   padding-top: 12px;"
        "   color: #eef2ff;"
        "}"
        ""
        "QGroupBox::title {"
        "   subcontrol-origin: margin;"
        "   left: 12px;"
        "   padding: 0 8px 0 8px;"
        "   color: #3b82f6;"
        "   font-weight: bold;"
        "}"
        ""
        "QLineEdit, QTextEdit {"
        "   background-color: rgba(0, 0, 0, 0.4);"
        "   border: 1px solid #3b82f6;"
        "   border-radius: 12px;"
        "   padding: 10px;"
        "   color: #eef2ff;"
        "}"
        ""
        "QTabWidget::pane {"
        "   background-color: rgba(18, 25, 45, 0.6);"
        "   border: 1px solid rgba(59, 130, 246, 0.2);"
        "   border-radius: 16px;"
        "}"
        ""
        "QTabBar::tab {"
        "   background-color: transparent;"
        "   padding: 8px 16px;"
        "   margin-right: 4px;"
        "   border-top-left-radius: 12px;"
        "   border-top-right-radius: 12px;"
        "}"
        ""
        "QTabBar::tab:selected {"
        "   background-color: #3b82f6;"
        "   color: white;"
        "}"
        ""
        "QTabBar::tab:hover {"
        "   background-color: rgba(59, 130, 246, 0.3);"
        "}"
        ""
        "QScrollBar:vertical {"
        "   background-color: rgba(18, 25, 45, 0.6);"
        "   width: 12px;"
        "   border-radius: 6px;"
        "}"
        ""
        "QScrollBar::handle:vertical {"
        "   background-color: #3b82f6;"
        "   border-radius: 6px;"
        "   min-height: 30px;"
        "}"
        ""
        "QScrollBar::handle:vertical:hover {"
        "   background-color: #2563eb;"
        "}"
        ""
        "QMenuBar {"
        "   background-color: rgba(18, 25, 45, 0.6);"
        "   color: #eef2ff;"
        "}"
        ""
        "QMenuBar::item:selected {"
        "   background-color: #3b82f6;"
        "}"
        ""
        "QMenu {"
        "   background-color: #0b0e17;"
        "   border: 1px solid rgba(59, 130, 246, 0.2);"
        "}"
        ""
        "QMenu::item:selected {"
        "   background-color: #3b82f6;"
        "}"
        "";
    
    app->setStyleSheet(styleSheet);
}
